### ISSUE TITLE
tx rejected: insufficient energy

### ISSUE THREAD

**Issue by yucheng-Li** [meterio/tokenERC20#1]
yuchengli@liyuchengdeMacBook-Pro tokenERC20 % npx hardhat run scripts/deployToken.ts
? 选择网络: metertest (83) : https://rpctest.meter.io
load network config: /Volumes/PSSD/private_code/bootcamp/tokenERC20/deployments/metertest/config.json
使用 hardhat.config.ts 中配置的rpc:  https://rpctest.meter.io
Signer: 0xDF0ae3aF6a860bD15d36AA4D294EeCae964319b0
? 输入Gas price: 2000000
? 输入Token name: BOOT
? 输入Token symbol: BOT
? 输入初始供应量(单位:wei): 100000000000000000000
? 输入nonce: 1450047622

load contract info: /Volumes/PSSD/private_code/bootcamp/tokenERC20/deployments/metertest/ERC20MinterBurnerPauser.json
Estimated Gas: 2493143
/Volumes/PSSD/private_code/bootcamp/tokenERC20/node_modules/ethers/src.ts/utils/errors.ts:694
            error = new Error(message);
                    ^
Error: could not coalesce error (error={ "code": -2, "message": "tx rejected: insufficient energy" }, payload={ "id": 15, "jsonrpc": "2.0", "method": "eth_sendRawTransaction", "params":

How do I fill in a suitable value ？

**Comment by xiaohanzhu** [comment]
You don't have any tokens in your testnet account.  [0xDF0ae3aF6a860bD15d36AA4D294EeCae964319b0](https://scan-warringstakes.meter.io/address/0xdf0ae3af6a860bd15d36aa4d294eecae964319b0)
That is why your tx was rejected.  Here is the testnet faucet https://faucet-warringstakes.meter.io/
